// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928065140_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceCommand", b =>
                {
                    b.Property<int>("DeviceCommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceCommandId"));

                    b.Property<int>("CommandType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("PlantDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WaterAmountMl")
                        .HasColumnType("int");

                    b.HasKey("DeviceCommandId");

                    b.HasIndex("PlantDeviceId");

                    b.ToTable("DeviceCommands");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceEvent", b =>
                {
                    b.Property<int>("DeviceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceEventId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("PlantDeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<int?>("WaterAmountMl")
                        .HasColumnType("int");

                    b.HasKey("DeviceEventId");

                    b.HasIndex("PlantDeviceId");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceReading", b =>
                {
                    b.Property<int>("DeviceReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceReadingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ReadingType")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("DeviceReadingId");

                    b.HasIndex("PlantDeviceId");

                    b.ToTable("DeviceReadings");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HealthProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<int>("PlantPhotoId")
                        .HasColumnType("int");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("PlantPhotoId")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.DiagnosisProblem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Probability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProblemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("DiagnosisProblems");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoilMoistureLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlantId");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.Property<int>("PlantPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantPhotoId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("PlantPhotoId");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantPhotos");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DiagnosisId")
                        .IsUnique();

                    b.HasIndex("PlantId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.ScheduleTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantDevice", b =>
                {
                    b.Property<int>("PlantDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantDeviceId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("PlantDeviceId");

                    b.HasIndex("PlantId");

                    b.HasIndex("DeviceId", "PlantId")
                        .IsUnique();

                    b.ToTable("PlantDevices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.HasOne("PlantCare.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceCommand", b =>
                {
                    b.HasOne("PlantDevice", null)
                        .WithMany()
                        .HasForeignKey("PlantDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceEvent", b =>
                {
                    b.HasOne("PlantDevice", null)
                        .WithMany()
                        .HasForeignKey("PlantDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceReading", b =>
                {
                    b.HasOne("PlantDevice", null)
                        .WithMany()
                        .HasForeignKey("PlantDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plants.PlantPhoto", "PlantPhoto")
                        .WithOne("Diagnosis")
                        .HasForeignKey("PlantCare.Api.Models.Diagnoses.Diagnosis", "PlantPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantPhoto");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.DiagnosisProblem", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Diagnoses.Diagnosis", "Diagnosis")
                        .WithMany("Problems")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("Photos")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Diagnoses.Diagnosis", "Diagnosis")
                        .WithOne("Schedule")
                        .HasForeignKey("PlantCare.Api.Models.Schedules.Schedule", "DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("Schedules")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.ScheduleTask", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Schedules.Schedule", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PlantDevice", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany("PlantDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("PlantDevices")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.Navigation("PlantDevices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.Navigation("Problems");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PlantDevices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.User", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
