// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928113018_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlantCare.Api.Models.Auth.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReplacedByRefreshTokenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Automation.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("IrrigationZoneId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("AlertId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IrrigationZoneId");

                    b.HasIndex("PlantId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Alerts", t =>
                        {
                            t.HasCheckConstraint("CK_Alert_SingleResource", "(CASE WHEN [PlantId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [DeviceId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [IrrigationZoneId] IS NOT NULL THEN 1 ELSE 0 END) <= 1");
                        });
                });

            modelBuilder.Entity("PlantCare.Api.Models.Automation.PhotoCaptureSchedule", b =>
                {
                    b.Property<int>("PhotoCaptureScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoCaptureScheduleId"));

                    b.Property<int>("CameraChannelId")
                        .HasColumnType("int");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("PhotoCaptureScheduleId");

                    b.HasIndex("CameraChannelId");

                    b.HasIndex("PlantId");

                    b.ToTable("PhotoCaptureSchedules");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("DeviceId");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceChannel", b =>
                {
                    b.Property<int>("DeviceChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceChannelId"));

                    b.Property<double?>("CalibrationOffset")
                        .HasColumnType("float");

                    b.Property<double?>("CalibrationScale")
                        .HasColumnType("float");

                    b.Property<int>("ChannelType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceChannelId");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceChannels");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceCommand", b =>
                {
                    b.Property<int>("DeviceCommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceCommandId"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("CommandType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("WaterAmountMl")
                        .HasColumnType("int");

                    b.HasKey("DeviceCommandId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.ToTable("DeviceCommands");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceEvent", b =>
                {
                    b.Property<int>("DeviceEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceEventId"));

                    b.Property<int?>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int?>("DeviceCommandId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("IrrigationZoneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<int?>("WaterAmountMl")
                        .HasColumnType("int");

                    b.Property<int>("WaterAmountSource")
                        .HasColumnType("int");

                    b.HasKey("DeviceEventId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DeviceCommandId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IrrigationZoneId");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceReading", b =>
                {
                    b.Property<int>("DeviceReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceReadingId"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadingType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("DeviceReadingId");

                    b.HasIndex("ChannelId", "ReadingType", "MeasuredAt")
                        .IsUnique();

                    b.ToTable("DeviceReadings");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiagnosisId"));

                    b.Property<string>("AiModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiModelVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnalysisStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HealthProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<int>("PlantPhotoId")
                        .HasColumnType("int");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiagnosisId");

                    b.HasIndex("PlantPhotoId")
                        .IsUnique();

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.DiagnosisProblem", b =>
                {
                    b.Property<int>("ProblemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<string>("Prevention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Probability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ProblemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("DiagnosisProblems");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Farms.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("FarmId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Farms.Plot", b =>
                {
                    b.Property<int>("PlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlotId"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geography");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CropType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlotId");

                    b.HasIndex("FarmId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationConfig", b =>
                {
                    b.Property<int>("IrrigationConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrrigationConfigId"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ConfirmedIsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ConfirmedMaxDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("ConfirmedMaxReadingAgeSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("ConfirmedPauseBetweenIrrigationsSeconds")
                        .HasColumnType("int");

                    b.Property<double?>("ConfirmedStartThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("ConfirmedStopThreshold")
                        .HasColumnType("float");

                    b.Property<int?>("ConfirmedVersion")
                        .HasColumnType("int");

                    b.Property<int>("IrrigationZoneId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxDurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MaxReadingAgeSeconds")
                        .HasColumnType("int");

                    b.Property<int>("MoistureSensorChannelId")
                        .HasColumnType("int");

                    b.Property<int>("PauseBetweenIrrigationsSeconds")
                        .HasColumnType("int");

                    b.Property<double>("StartThreshold")
                        .HasColumnType("float");

                    b.Property<double>("StopThreshold")
                        .HasColumnType("float");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("IrrigationConfigId");

                    b.HasIndex("IrrigationZoneId")
                        .IsUnique();

                    b.HasIndex("MoistureSensorChannelId");

                    b.ToTable("IrrigationConfigs", t =>
                        {
                            t.HasCheckConstraint("CK_IrrigationConfig_ThresholdOrder", "[StartThreshold] < [StopThreshold]");
                        });
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationZone", b =>
                {
                    b.Property<int>("IrrigationZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrrigationZoneId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<int>("ValveChannelId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("IrrigationZoneId");

                    b.HasIndex("PlotId");

                    b.HasIndex("ValveChannelId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("IrrigationZones");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationZonePlant", b =>
                {
                    b.Property<int>("IrrigationZonePlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrrigationZonePlantId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IrrigationZoneId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("IrrigationZonePlantId");

                    b.HasIndex("IrrigationZoneId", "PlantId")
                        .IsUnique();

                    b.HasIndex("IrrigationZoneId", "WorkspaceId");

                    b.HasIndex("PlantId", "WorkspaceId");

                    b.ToTable("IrrigationZonePlants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoilMoistureLevel")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("PlantId");

                    b.HasIndex("PlotId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.Property<int>("PlantPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantPhotoId"));

                    b.Property<int?>("CameraChannelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PlantPhotoId");

                    b.HasIndex("CameraChannelId");

                    b.HasIndex("PlantId");

                    b.ToTable("PlantPhotos");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.PlotObservation", b =>
                {
                    b.Property<int>("PlotObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlotObservationId"));

                    b.Property<double?>("Ndvi")
                        .HasColumnType("float");

                    b.Property<int>("PlotId")
                        .HasColumnType("int");

                    b.Property<string>("ProcessingVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("SatelliteSceneId")
                        .HasColumnType("int");

                    b.Property<double>("ValidCoveragePercent")
                        .HasColumnType("float");

                    b.HasKey("PlotObservationId");

                    b.HasIndex("SatelliteSceneId");

                    b.HasIndex("PlotId", "SatelliteSceneId")
                        .IsUnique();

                    b.ToTable("PlotObservations");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.SatelliteCheck", b =>
                {
                    b.Property<int>("SatelliteCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatelliteCheckId"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.HasKey("SatelliteCheckId");

                    b.HasIndex("FarmId");

                    b.ToTable("SatelliteChecks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.SatelliteScene", b =>
                {
                    b.Property<int>("SatelliteSceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatelliteSceneId"));

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("ResolutionMeters")
                        .HasColumnType("float");

                    b.HasKey("SatelliteSceneId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("SatelliteScenes");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiagnosisId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("DiagnosisId")
                        .IsUnique()
                        .HasFilter("[DiagnosisId] IS NOT NULL");

                    b.HasIndex("PlantId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.ScheduleTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("ScheduleTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Workspaces.Workspace", b =>
                {
                    b.Property<int>("WorkspaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkspaceId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("WorkspaceId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Workspaces.WorkspaceMember", b =>
                {
                    b.Property<int>("WorkspaceMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkspaceMemberId"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("WorkspaceMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique();

                    b.ToTable("WorkspaceMembers");
                });

            modelBuilder.Entity("PlantDevice", b =>
                {
                    b.Property<int>("PlantDeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantDeviceId"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.HasKey("PlantDeviceId");

                    b.HasIndex("PlantId");

                    b.HasIndex("DeviceId", "PlantId")
                        .IsUnique();

                    b.ToTable("PlantDevices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Auth.RefreshToken", b =>
                {
                    b.HasOne("PlantCare.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Automation.Alert", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantCare.Api.Models.Irrigation.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("IrrigationZone");

                    b.Navigation("Plant");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Automation.PhotoCaptureSchedule", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "CameraChannel")
                        .WithMany()
                        .HasForeignKey("CameraChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CameraChannel");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.HasOne("PlantCare.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceChannel", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany("Channels")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceCommand", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceEvent", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Devices.DeviceCommand", "DeviceCommand")
                        .WithMany()
                        .HasForeignKey("DeviceCommandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Irrigation.IrrigationZone", "IrrigationZone")
                        .WithMany()
                        .HasForeignKey("IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Channel");

                    b.Navigation("Device");

                    b.Navigation("DeviceCommand");

                    b.Navigation("IrrigationZone");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.DeviceReading", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plants.PlantPhoto", "PlantPhoto")
                        .WithOne("Diagnosis")
                        .HasForeignKey("PlantCare.Api.Models.Diagnoses.Diagnosis", "PlantPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantPhoto");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.DiagnosisProblem", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Diagnoses.Diagnosis", "Diagnosis")
                        .WithMany("Problems")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Farms.Farm", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Farms.Plot", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Farms.Farm", "Farm")
                        .WithMany("Plots")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationConfig", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Irrigation.IrrigationZone", "IrrigationZone")
                        .WithOne("Config")
                        .HasForeignKey("PlantCare.Api.Models.Irrigation.IrrigationConfig", "IrrigationZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "MoistureSensorChannel")
                        .WithMany()
                        .HasForeignKey("MoistureSensorChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationZone");

                    b.Navigation("MoistureSensorChannel");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationZone", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Farms.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "ValveChannel")
                        .WithMany()
                        .HasForeignKey("ValveChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("ValveChannel");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationZonePlant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Irrigation.IrrigationZone", "IrrigationZone")
                        .WithMany("Plants")
                        .HasForeignKey("IrrigationZoneId", "WorkspaceId")
                        .HasPrincipalKey("IrrigationZoneId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId", "WorkspaceId")
                        .HasPrincipalKey("PlantId", "WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IrrigationZone");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Farms.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantCare.Api.Models.User", "User")
                        .WithMany("Plants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.DeviceChannel", "CameraChannel")
                        .WithMany()
                        .HasForeignKey("CameraChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("Photos")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CameraChannel");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.PlotObservation", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Farms.Plot", "Plot")
                        .WithMany()
                        .HasForeignKey("PlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Satellite.SatelliteScene", "SatelliteScene")
                        .WithMany("Observations")
                        .HasForeignKey("SatelliteSceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plot");

                    b.Navigation("SatelliteScene");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.SatelliteCheck", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Farms.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Diagnoses.Diagnosis", "Diagnosis")
                        .WithOne("Schedule")
                        .HasForeignKey("PlantCare.Api.Models.Schedules.Schedule", "DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("Schedules")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.ScheduleTask", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Schedules.Schedule", "Schedule")
                        .WithMany("Tasks")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Workspaces.WorkspaceMember", b =>
                {
                    b.HasOne("PlantCare.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Workspaces.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("PlantDevice", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Devices.Device", "Device")
                        .WithMany("PlantDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlantCare.Api.Models.Plants.Plant", "Plant")
                        .WithMany("PlantDevices")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Devices.Device", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("PlantDevices");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Diagnoses.Diagnosis", b =>
                {
                    b.Navigation("Problems");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Farms.Farm", b =>
                {
                    b.Navigation("Plots");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Irrigation.IrrigationZone", b =>
                {
                    b.Navigation("Config");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.Plant", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PlantDevices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plants.PlantPhoto", b =>
                {
                    b.Navigation("Diagnosis");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Satellite.SatelliteScene", b =>
                {
                    b.Navigation("Observations");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Schedules.Schedule", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.User", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Workspaces.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
